Article.delete_all
Comment.delete_all

Article.create!(title: 'TEST1Sharable analyzing model', url:'http://erdman.org/letha.romaguera', created_at:'2014-05-13 02:52:04 UTC')
Article.create!(title: 'Distributed coherent array', url:'http://lynchwehner.com/aurelia', created_at:'2014-05-13 02:52:19 UTC')
Article.create!(title: 'Persistent local concept', url:'http://bradtke.name/cornelius', created_at:'2014-05-13 02:52:24 UTC')
Article.create!(title: 'Programmable demand-driven Graphical User Interface', url:'http://fayrunolfsdottir.org/cydney.bogisich', created_at:'2014-05-13 02:52:31 UTC')
Article.create!(title: 'Innovative coherent project', url:'http://leannonschamberger.org/leonora', created_at:'2014-05-13 02:52:31 UTC')
Article.create!(title: 'Self-enabling bi-directional internet solution', url:'http://bergstrom.net/pierce_purdy', created_at:'2014-05-13 02:52:32 UTC')
Article.create!(title: 'Switchable content-based collaboration', url:'http://murray.com/nash.littel', created_at:'2014-05-13 02:52:32 UTC')
Article.create!(title: 'Stand-alone didactic superstructure', url:'http://hyatt.net/gina.dubuque', created_at:'2014-05-13 02:52:32 UTC')
Article.create!(title: 'Diverse motivating support', url:'http://schowalter.com/camylle', created_at:'2014-05-13 02:52:33 UTC')
Article.create!(title: 'Total fault-tolerant budgetary management', url:'http://ziemann.net/wilfred_wisoky', created_at:'2014-05-13 02:52:33 UTC')
Article.create!(title: 'Devolved regional model', url:'http://block.com/astrid', created_at:'2014-05-13 02:52:34 UTC')
Article.create!(title: 'Centralized optimizing projection', url:'http://townegutkowski.com/everette_kautzer', created_at:'2014-05-13 02:52:34 UTC')
Article.create!(title: 'TEST FINAL Go time!', url:'http://gotime.com', created_at:'2014-05-13 03:35:47 UTC')

Comment.create!(message: 'TEST1 Non est minima sunt.', created_at:'Non est minima sunt.')
Comment.create!(message: 'Recusandae itaque et et.', created_at:'Recusandae itaque et et.')
Comment.create!(message: 'Est animi vel corrupti maxime aut.', created_at:'Est animi vel corrupti maxime aut.')
Comment.create!(message: 'Aspernatur quod a libero fugit facilis voluptatem natus ad.', created_at:'Aspernatur quod a libero fugit facilis voluptatem natus ad.')
Comment.create!(message: 'Quae odio sed voluptatem eum dolor cum.', created_at:'Quae odio sed voluptatem eum dolor cum.')
Comment.create!(message: 'Magni non et et sunt occaecati quia ut.', created_at:'Magni non et et sunt occaecati quia ut.')
Comment.create!(message: 'Fuga sapiente atque est reiciendis sunt aut cum.', created_at:'Fuga sapiente atque est reiciendis sunt aut cum.')
Comment.create!(message: 'Dolorem ad pariatur aliquam quod temporibus iusto.', created_at:'Dolorem ad pariatur aliquam quod temporibus iusto.')
Comment.create!(message: 'Non quo accusantium sint.', created_at:'Non quo accusantium sint.')
Comment.create!(message: 'Rerum assumenda enim quibusdam minus quo dignissimos rem autem.', created_at:'Rerum assumenda enim quibusdam minus quo dignissimos rem autem.')
Comment.create!(message: 'Nisi est quo ut qui occaecati dolorem natus minus.', created_at:'Nisi est quo ut qui occaecati dolorem natus minus.')
Comment.create!(message: 'Placeat et exercitationem nihil asperiores dolor delectus.', created_at:'Placeat et exercitationem nihil asperiores dolor delectus.')
Comment.create!(message: 'Modi sunt ab est nihil aspernatur et maxime.', created_at:'Modi sunt ab est nihil aspernatur et maxime.')
Comment.create!(message: 'Officia ut recusandae nulla illum placeat.', created_at:'Officia ut recusandae nulla illum placeat.')
Comment.create!(message: 'Eum nisi qui aut rerum.', created_at:'Eum nisi qui aut rerum.')
Comment.create!(message: 'Ab consequatur nemo qui aut ipsa rerum molestias.', created_at:'Ab consequatur nemo qui aut ipsa rerum molestias.')
Comment.create!(message: 'Voluptatibus qui iure aut saepe ut atque.', created_at:'Voluptatibus qui iure aut saepe ut atque.')
Comment.create!(message: 'Eius autem ut neque molestiae omnis.', created_at:'Eius autem ut neque molestiae omnis.')
Comment.create!(message: 'Facilis explicabo qui ipsam nesciunt inventore.', created_at:'Facilis explicabo qui ipsam nesciunt inventore.')
Comment.create!(message: 'Sapiente et est nostrum labore.', created_at:'Sapiente et est nostrum labore.')
Comment.create!(message: 'Tempore illo quo qui est vel quasi.', created_at:'Tempore illo quo qui est vel quasi.')
Comment.create!(message: 'Ullam exercitationem nostrum quis fugit aut neque.', created_at:'Ullam exercitationem nostrum quis fugit aut neque.')
Comment.create!(message: 'Pariatur ut et sed.', created_at:'Pariatur ut et sed.')
Comment.create!(message: 'TEST FINAL Ut odit et earum vitae a molestiae assumenda.', created_at:'Ut odit et earum vitae a molestiae assumenda.')
